name: AlineBalasGourmet - CD (Production) ğŸ­
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  DeployProduction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI ğŸ“¦
        run: yarn global add vercel@latest
      - name: Pull information from Vercel ğŸ“¥
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project ğŸ—ï¸
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project ğŸ“¤
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
