name: AlineBalasGourmet - CI/CD
on: [push]
jobs:
  start:
    name: Start
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set NodeJs ğŸŸ¢
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        name: Install Lib's ğŸ“¦

  lint-staged:
    name: Lint-Staged
    runs-on: ubuntu-latest

    steps:
      - run: yarn lint-staged
        name: Lint-Staged ğŸ”

  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - run: yarn test
        name: QA ğŸ§ª
