name: CI/CD
on: [push]
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set NodeJs ðŸŸ¢
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        name: Install Lib's ðŸ“¦
      - run: yarn test
        name: QA ðŸ§ª
