name: AlineBalasGourmet - CI/CD (Preview) ğŸ­
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set NodeJs ğŸŸ¢
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install Lib's ğŸ“¦
        run: yarn install
      - name: QA ğŸ§ª
        run: yarn test::ci
      - name: TypeCheck
        run: yarn type-check

  DeployPreview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI ğŸ“¦
        run: yarn global add vercel@latest
      - name: Pull information from Vercel ğŸ“¥
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project ğŸ—ï¸
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project ğŸ“¤
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
